# Generated by Django 5.1.1 on 2024-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ticketpurchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
