# Generated by Django 5.1.1 on 2024-12-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_ticketpurchase_options_ticketpurchase_paid_and_more'),
        ('pages', '0003_remove_invoice_id_alter_invoice_new_id'),
    ]

    operations = [
    ]
