# Generated by Django 5.1.1 on 2024-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_merge_20241221_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPurchase',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_intent_id',
            field=models.CharField(default='1', max_length=400),
            preserve_default=False,
        ),
    ]
