# Generated by Django 5.1.1 on 2024-12-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_ticketpurchase_invoice_payment_intent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='new_id',
            new_name='id',
        ),
    ]
